### ISSUE TITLE
False Positive Reports

### ISSUE THREAD

**Issue by ghost** [vani42069/Pet-cheat-detector#2]
[Line of code in question.](https://github.com/vani42069/Pet-cheat-detector/blob/4b6b20b4952efe5420a0a9b1793b9650fea7e807/index.js#L51)

No data about passive skills is saved, meaning every time a passive skill will proc it will generate *false positive* cheaters.

Should be either fixed or made clear to people about this issue.

**Comment by vani42069** [comment]
> [Line of code in question.](https://github.com/vani42069/Pet-cheat-detector/blob/4b6b20b4952efe5420a0a9b1793b9650fea7e807/index.js#L51)
> 
> No data about passive skills is saved, meaning every time a passive skill will proc it will generate _false positive_ cheaters.
> 
> Should be either fixed or made clear to people about this issue.

passive skills should trigger difference
(no S_ACTION_STAGE)

**Comment by ghost** [comment]
Not sure if this version got updated, got to test a version tuesday 25th, went with a friend in pk and tried to proc barrier normally.

Turned out it was generating false positives because my friend was clearly not running toolbox.

**Comment by vani42069** [comment]
> Not sure if this version got updated, got to test a version tuesday 25th, went with a friend in pk and tried to proc barrier normally.
> 
> Turned out it was generating false positives because my friend was clearly not running toolbox.

Yes its updated, early version had false positives , but i doubt we are talking about the same code lol
