### ISSUE TITLE
error

### ISSUE THREAD

**Issue by teraoo** [vani42069/Pet-cheat-detector#6]
![image](https://user-images.githubusercontent.com/40299748/60340567-40acc580-99ac-11e9-8d0b-d82eba0bcba3.png)

**Comment by vani42069** [comment]
Use Toolbox

https://discord.gg/dUNDDtw

**Comment by teraoo** [comment]
no i use only pink´s  can you not rewrite?

**Comment by vani42069** [comment]
No

**Comment by Leyki** [comment]
bro please rewrite...

**Comment by vani42069** [comment]
bro im ILLITERATE
