### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by keito201** [vani42069/Pet-cheat-detector#9]

**Comment by keito201** [comment]
Do i need to party up with someone or pk him or does it auto detect in all server?

**Comment by vani42069** [comment]
Be in the same area/channel

**Comment by keito201** [comment]
So if someone is in arx umbra and im in highwatch can i detect him?

**Comment by keito201** [comment]
and what about if someone is in schm and im in highwatch?

**Comment by vani42069** [comment]
No , If youre in Tria channel 1 , if someone pops wrong ids in Tria channel 1 , youll get the message,  If youre in the same party in the same dungeon , if someone pops wrong ids , youll get the message.

**Comment by Snugglez** [comment]
Tl;dr if they are loaded on your side and they use a pet skill they dont have, you detect it

**Comment by keito201** [comment]
oh loaded okay thank you :)
